/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Lab.COMP;

public class Library {
	
	/*Add this func*/
	public static void main(String arg[]) {
		System.out.println("Hello, World!");	
	}
	
	
    public boolean someLibraryMethod() {
        return true;
    }
}
